apiVersion: apps/v1
kind: Deployment
metadata:
  name: exp1-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exp1-deployment
  template:
    metadata:
      labels:
        app: exp1-deployment
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - kwok
      tolerations:
      - key: "kwok.x-k8s.io/node"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: exp1-container-a
        image: fake-image
        resources:
         requests:
           memory: 100Mi
           cpu: 1000m
      - name: exp1-container-b
        image: fake-image
        resources:
         requests:
           memory: 100Mi
           cpu: 1000m
