apiVersion: apps/v1
kind: Deployment
metadata:
  name: exp1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exp1-deployment
  template:
    metadata:
      labels:
        app: exp1-deployment
    spec:
      containers:
      - name: exp1-container-a
        image: fake
        resources:
          requests:
            cpu: 1000m
            memory: 100Mi
      - name: exp1-container-b
        image: fake
        resources:
          requests:
            cpu: 1000m
            memory: 100Mi
