kind: ClusterResourceUsage
apiVersion: kwok.x-k8s.io/v1alpha1
metadata:
  name: exp-usage
spec:
  selector:
    matchNamespaces:
    - default
  usages:
  - containers:
    - exp1-container-a
    usage:
      cpu:
        value: 700m
      memory:
        value: 1Mi
  - containers:
    - exp1-container-b
    usage:
      cpu:
        value: 200m
      memory:
        value: 1Mi
  - usage:
      cpu:
        value: 1m
      memory:
        value: 1Mi