kind: ResourceUsage
apiVersion: kwok.x-k8s.io/v1alpha1
metadata:
  name: exp1-deployment
  namespace: default
spec:
  usages:
  - containers:
    - exp1-container-a
    usage:
      cpu:
        value: 700m
