apiVersion: apps/v1
kind: Deployment
metadata:
 name: exp5-deployment
spec:
 selector:
   matchLabels:
     run: exp5-deployment
 replicas: 1
 template:
   metadata:
     labels:
       run: exp5-deployment
   spec:
     containers:
     - name: exp5-container-a
       image: caetanobca/stress-ng
       args: 
        - "stress-ng"
        - "--vm"
        - "1"
        - "--vm-bytes"
        - "100M"
        - "--timeout"
        - "15m"
       resources:
         requests:
           memory: 100M
           cpu: 1
     - name: exp5-container-b
       image: caetanobca/stress-ng
       args: 
        - "stress-ng"
        - "--vm"
        - "1"
        - "--vm-bytes"
        - "100M"
        - "--timeout"
        - "15m"
       resources:
         requests:
           memory: 400M
           cpu: 1